
dev_lines = [
    "Is it okay if I walk you home? My heart seems to follow wherever you go.\n",
    "If beauty were a moment, you'd be an eternity.\n",
    "Did we just share an elevator? Because I believe we have some serious uplifted chemistry.\n",
    "I must be a snowflake because I've fallen for you.\n",
    "Every time I see you, it feels like I've discovered a new shade of color.\n",
    "If stars would shine every time I thought of you, the night sky would never be dark.\n",
    "Do you believe in love at first sight, or should I walk by again?\n",
    "Your voice is my favorite sound, and your name is my favorite noun.\n",
    "If I were to rewrite the alphabet, I'd put U and I together.\n",
    "Have you been to the doctor recently? Because I think you've got a case of being mesmerizing.\n",
    "I wouldn't need a camera to savor this moment; I just need you.\n",
    "Is it hot in here, or is it just the aura of warmth you radiate?\n",
    "I tried finding the perfect line to make you smile, but then I realized you are the line.\n",
    "If you were a vegetable, you'd be a 'cute-cumber.'\n",
    "If life was a song, your smile would be the melody that gets stuck in my head.\n",
    "I'm not a photographer, but I can surely picture us together.\n",
    "If you were a fruit, you'd be a fine-apple.\n",
    "I'm not sure if it was the sparkle in your eyes or your radiant smile, but something just lit up my world.\n",
    "Do you mind holding my hand? I want to be sure I'm not dreaming.\n",
    "I've been trying to tie my shoes, but I can't stop tripping over my thoughts of you.\n",
    "Is there a rainbow today? Because I've just found my pot of gold in you.\n",
    "Do you have a map? I keep getting lost in your eyes.\n",
    "If you were a star, you'd outshine the entire galaxy.\n",
    "I'm not a wishful thinker, but with you, I believe in fairy tales.\n",
    "I thought happiness started with an H, but mine starts with U.\n",
    "Your smile must be a black hole because it's irresistibly attractive.\n",
    "Are you Wi-fi? Because I'm feeling a connection.\n",
    "If kisses were snowflakes, I'd send you a blizzard.\n",
    "Do you have a Band-Aid? I just scraped my knee falling for you.\n",
    "Your presence makes my heart race, but it's a marathon I never want to finish.\n",
    "If beauty were a crime, you'd be serving a life sentence.\n",
    "Did it hurt? When you fell from the stars and landed in my world?\n",
    " I'm not a genie, but I can make your dreams come true.\n",
    "Every song I hear reminds me of you, even the ones I haven't heard yet.\n",
    "I never believed in magic until I saw you.\n",
    "If you were words on a page, you'd be the fine print.\n",
    " Are you made of copper and tellurium? Because you're Cu-Te.\n",
    "Can I follow you? Because my mom told me to follow my dreams.\n",
    "Your beauty could inspire poets and artists for generations.\n",
    "Do you believe in destiny? Because I think ours just intertwined.\n",
    "Are you a calculator? Because every time I look at you, things start adding up.\n",
    "Is your name Google? Because you have everything I've been searching for.\n",
    "Do you have a name, or can I call you mine?\n",
    "Are you a magician? Every time I look at you, everyone else disappears.\n",
    "Do you like basketball? Because when I saw you, my heart did a slam dunk.\n",
    "Are you a library book? Because I can't help but check you out.\n",
    "If you were a vegetable, you'd be a cutecumber.\n",
    "Do you have a sunburn or are you always this hot?\n",
    "Is your dad a boxer? Because you're a knockout.\n",
    "Are you a loan from a bank? Because you have my interest.\n",
    "Are you a campfire? Because you're hot and I want s'more.\n",
    "Do you have a pencil? Because I want to erase your past and write our future.\n",
    "Are you a parking ticket? Because you've got 'FINE' written all over you.\n",
    "If I could rearrange the alphabet, I would put U and I together.\n",
    "Are you a snowstorm? Because you make my heart race.\n",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.\n",
    "Is your dad a baker? Because you're a cutie pie.\n",
    "Are you a time traveler? Because I can see you in my future.\n",
    "Are you a candle? Because you light up my world.\n",
    "Are you a string? Because I can't stop finding myself attached to you.\n",
    "If you were a function, I'd call you every day.\n",
    "Are you a loop? Because I can't stop thinking about you again and again.\n",
    "You're the 'key' to my 'value'.\n",
    "If beauty were data, you'd be an overflow error.\n",
    "Are you a variable? Because I feel the need to declare my intentions.\n",
    "I think you've just incremented my heart's counter.\n",
    "You're the API to my application.\n",
    "If relationships were algorithms, ours would be a perfect match.\n",
    "Your presence makes my system run at optimal efficiency.\n",
    "If you were an exception, I'd catch you.\n",
    "You must be a compiler because every time I see you, my code becomes runnable.\n",
    "I'm not a photographer, but I can picture us in an endless loop together.\n",
    "In the world of binary, you are the one for me.\n",
    "I've got a lot of lines of code, but none as intriguing as the story of us.\n",
    "Forget the cloud, you've taken up all the storage in my heart.\n",
    "I don't need version control to know you're my final commit.\n",
    "Let's merge our branches and build a beautiful codebase together.\n",
    "Do you believe in parallel universes? Because in every one I've imagined, it's always been you and me.\n",
    "You must be a packet because I can't help but sniff you out in a crowd.\n",
    "Are you an algorithm? Because every part of me wants to solve you.\n",
    "Do you know JavaScript? Because you make my heart race asynchronously.\n",
    "If I were to traverse the nodes of my heart, every path would lead to you.\n",
    "In the Git of life, I'd never want to revert our commit.\n",
    "Are you a CSS file? Because without you, my life would be unstyled.\n",
    "You must be a bug, because I just can't shake you off my mind.\n",
    "If hearts had firewalls, you'd have bypassed mine ages ago.\n",
    "Are you a Boolean? Because true or false, my heart points to you.\n",
    "In the world of objects, you are my favorite instance.\n",
    "If attraction were a programming language, ours would be high-level.\n",
    "Are you a kernel? Because my heart feels an urge to dive deeper into you.\n",
    "Do you like Java? Because you've Objectified my affections.\n",
    "I'd never put our relationship in a try-catch block, because I never want to handle an exception with us. \n",
    "You're not just a semicolon; you're the statement that completes me.\n",
    "In the IDE of life, you've just become my favorite extension.\n",
    "If I were a coder, I'd refactor my life to include more of you.\n",
    "You're like the most elegant code I've ever seen; concise, beautiful, and effective.\n",
    "You've stolen the ASCII to my heart.\n",
    "You must be an exception, because I can't handle you properly.\n",
    "You must be an algorithm, because you have my heart running in O(1) time.\n",
    "Are you a piece of code? Because you're turning my software into hardware!\n",
    "Are you a compressed file? Because when I see you, my heart wants to unzip.\n",
    "I'm the RizzLord."
]

romantic_lines = [
    "Is it okay if I walk you home? My heart seems to follow wherever you go.",
    "If beauty were a moment, you'd be an eternity.",
    "Every time I see you, it feels like I've discovered a new shade of color",
    "If stars would shine every time I thought of you, the night sky would glisten.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Your voice is my favorite sound, and your name is my favorite noun.",
    "If I were to rewrite the alphabet, I'd put U and I together.",
    "I wouldn't need a camera to savor this moment; I just need you.",
    "Every song I hear reminds me of you, even the ones I haven't heard yet…",
    "I never believed in magic until I saw you.",
    "Your beauty could inspire poets and artists for generations.",
    "Do you believe in destiny? Because I think ours just intertwined.",
    "Your presence makes my heart race, but it's a marathon I never want to…",
    "If beauty were a crime, you'd be serving a life sentence.",
    "Every time I look at you, I believe in fairy tales.",
    "Thought happiness started with an H, but mine starts with U.",
    "Are you Wi-fi? Because I'm feeling a connection.",
    "Do you have a Band-Aid? I just scraped my knee falling for you.",
    "Is there a rainbow today? Because I've just found my pot of gold in you",
    "If you were a star, you'd outshine the entire galaxy.",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Your smile must be a black hole because it's irresistibly attractive.",
    "If you were words on a page, you'd be the fine print.",
    "Can I follow you? Because my mom told me to follow my dreams.",
    "Is your name Google? Because you have everything I've been searching for you",
    "Do you have a name, or can I call you mine?",
    "Are you a library book? Because I can't help but check you out.",
    "Do you have a pencil? Because I want to erase your past and write our future",
    "Is your dad a baker? Because you're a cutie pie.",
    "Are you a candle? Because you light up my world.",
    "Are you a string? Because I can't stop finding myself attached to you.",
    "If you were a function, I'd call you every day.",
    "Are you a loop? Because I can't stop thinking about you again and again",
]

clever_lines = [
    "Did we just share an elevator? Because I believe we have some serious …",
    "I must be a snowflake because I've fallen for you."
    "I tried finding the perfect line to make you smile, but then I realize…",
    "If you were a vegetable, you'd be a 'cute-cumber.'",
    "If life was a song, your smile would be the melody that gets stuck in …",
    "Is it hot in here, or is it just the aura of warmth you radiate?",
    "I've been trying to tie my shoes, but I can't stop tripping over my th…",
    "Do you have a map? I keep getting lost in your eyes.",
    "Did it hurt? When you fell from the stars and landed in my world?",
    "I'm not a genie, but I can make your dreams come true.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Are you a magician? Every time I look at you, everyone else disappears…",
    "Do you like basketball? Because when I saw you, my heart did a slam du…",
    "If you were a vegetable, you'd be a cutecumber.",
    "Do you have a sunburn, or are you always this hot?",
    "Is your dad a boxer? Because you're a knockout.",
    "Are you a loan from a bank? Because you have my interest.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Are you a parking ticket? Because you've got 'FINE' written all over y…",
    "Are you a snowstorm? Because you make my heart race.",
    "Are you a time traveler? Because I can see you in my future.",
]

geeky_lines = [
    "You're the 'key' to my 'value'.",
    "If beauty were data, you'd be an overflow error.",
    "Are you a variable? Because I feel the need to declare my intentions.",
    "I think you've just incremented my heart's counter.",
    "You're the API to my application.",
    "If relationships were algorithms, ours would be a perfect match.",
    "Your presence makes my system run at optimal efficiency.",
    "If you were an exception, I'd catch you.",
    "You must be a compiler because every time I see you, my code becomes r…",
    "I'm not a photographer, but I can picture us in an endless loop togeth…",
    "In the world of binary, you are the one for me.",
    "I've got a lot of lines of code, but none as intriguing as the story o…",
    "Forget the cloud, you've taken up all the storage in my heart.",
    "I don't need version control to know you're my final commit.",
    "Let's merge our branches and build a beautiful codebase together.",
    "Do you believe in parallel universes? Because in every one I've imagin…",
    "You must be a packet because I can't help but sniff you out in a crowd…",
    "Are you an algorithm? Because every part of me wants to solve you.",
    "Do you know JavaScript? Because you make my heart race asynchronously.",
    "If I were to traverse the nodes of my heart, every path would lead to …",
    "In the Git of life, I'd never want to revert our commit.",
    "Are you a CSS file? Because without you, my life would be unstyled.",
    "You must be a bug, because I just can't shake you off my mind.",
    "If hearts had firewalls, you'd have bypassed mine ages ago.",
    "Are you a Boolean? Because true or false, my heart points to you.",
    "In the world of objects, you are my favorite instance.",
    "If attraction were a programming language, ours would be high-level.",
    "Are you a kernel? Because my heart feels an urge to dive deeper into y…",
    "Do you like Java? Because you've Objectified my affections.",
    "I'd never put our relationship in a try-catch block, because I never w…",
    "You're not just a semicolon; you're the statement that completes me.",
    "In the IDE of life, you've just become my favorite extension.",
    "If I were a coder, I'd refactor my life to include more of you.",
    "You're like the most elegant code I've ever seen; concise, beautiful, …",
    "You have stolen the ASCII to my heart.",
    "You must be an exception, because I can't handle you properly.",
    "You must be an algorithm, because you have my heart running in O(1) ti…",
    "Are you a piece of code? Because you're turning my software into hardw…",
    "Are you a compressed file? Because when I see you, my heart wants to u…"
]

templates =  [
    "Do you have a {}? Because whenever I look at you, everyone else disappears.",
    "Are you a {}? Because every time I think of you, I smile.",
    "Do you have a map? I keep getting lost in your {}.",
    "If beauty were time, you'd be an {}.",
    "I'm not a photographer, but I can picture us together in a {}.",
    "Can I follow you home? Cause my parents always told me to follow my {}.",
    "Is your name Google? Because you have everything I've been searching for in the {}.",
    "Are you made of copper and tellurium? Because you're {}.",
    "Do you like Star Wars? Because Yoda only one for me in the {}.",
    "If you were a {} on a McDonald's menu, you'd be a McGorgeous.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for {}.",
    "Is it hot in here or is it just the {} we have together?",
    "If you were a vegetable, you'd be a {}.",
    "I must be a {} because I am attracted to your magnetic field.",
    "Is there an airport nearby or is that just my heart taking {}?",
    "You must be a magician because whenever I look at you, everyone else {}.",
    "If I could rearrange the alphabet, I'd put {} and {} together.",
    "Are you a {}? Because you're so fine you blow my mind.",
    "Do you have a pencil? Cause I want to erase your past and write our {}.",
    "Do you know what my shirt is made of? It's made of boyfriend {}."
]

user_lines = []

pickuplines = {
    'dev_lines': dev_lines,
    'romantic_lines': romantic_lines,
    'clever_lines': clever_lines,
    'geeky_lines': geeky_lines,
    'user_lines': user_lines,
    'all': dev_lines + romantic_lines + clever_lines + geeky_lines + user_lines
}

user_templates = templates