# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: pyrizz_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  

    - name: Install system dependencies for aiohttp
      run: sudo apt-get update && sudo apt-get install -y libffi-dev libssl-dev gcc

    - name: Upgrade setuptools and wheel
      run: pip install --upgrade setuptools wheel

    - name: Install aiohttp with pip to check for pre-built wheel availability
      run: pip install aiohttp || echo "Pre-built wheel not available for aiohttp; it will be built from source."

    - name: Install dependencies with Pipenv
      run: pip install pipenv && pipenv install --dev --verbose

    - name: Run tests
      run: pipenv run pytest tests/test_pyrizz.py